### ISSUE TITLE
Suggestion: Add "Deep Dungeon Only" filter to Enemies

### ISSUE THREAD

**Issue by Lexentale** [KangasZ/RadarPlugin#17]
I might be missing a setting somewhere, but it doesn't seem possible to only show enemies inside deep dungeons? I'd love to see enemy dots, their aggro radius and cones inside PotD/HoH/EO, but not anywhere else. Excellent addon otherwise, thank you for your work.

**Comment by KangasZ** [comment]
That is the current design, leftovers from prior builds never cleaned up or iterated on. Going to put some checks in since this exposed a bug either way. Will create a new default category that all deep dungeon or eureka mobs will default to given no other option - essentially making the config completely seperate between overworld and deep dungeons.

**Comment by KangasZ** [comment]
This has been updated. The current live version will default all enemy mobs to a 'catch all' bin. This is true for all deep dungeon and eureka zones. I hope this improves your experience!
