### ISSUE TITLE
Suggestion: Hidden Players And GM

### ISSUE THREAD

**Issue by xnuken** [KangasZ/RadarPlugin#25]
Ability to render GM's and other invisible players.

**Comment by KangasZ** [comment]
This requires the information to be sent to the client. If it is sent to the client, the option in utility called 'Show Only Visible' should show invisible players/GM. Otherwise 'Debug Mode' shows all objects regardless of any filtering. If you can verify that the information is indeed sent to the client, then I can put some work into it; shouldn't be too difficult.

GM/Invisible would most likely be captured already just filtered out in that setting. I can create an override that will ignore that setting if its a player character, and potentially even change display format.

**Comment by KangasZ** [comment]
A feature is being worked on in a dev branch that will override the invisible check normally applied to entities for players.

Again, this relies on the data being sent to the client and populated in the object table. I have no idea if either of these actions occur. However the feature will be useful since it shows players even when they are loading in and invisible regardless of GM stuff.
